run:
  timeout: 1m # default 1m
  tests: true # default true

linters-settings:
  errcheck:
    check-type-assertions: true # default false
    check-blank: true # default false
    ignore: "fmt:.*" # default fmt:.*
    exclude: "" # default ""
  govet:
    enable-all: true
    settings:
      shadow:
        strict: true # default false
  structcheck:
    exported-fields: true # default false
  unused:
    check-exported: true # default false
  varcheck:
    exported-fields: true # default false

  dupl:
    threshold: 150 # default 150
  funlen:
    lines: 60 # default 60
    statements: 40 # default 40
  gocognit:
    min-complexity: 15 # minimal code complexity to report, 30 by default (but we recommend 10-20)
  goconst:
    min-len: 3 # default 3
    min-occurrences: 3 # default 3
  gocritic:
    settings:
      captLocal:
        paramsOnly: false # default true
      elseif:
        skipBalanced: false # default true
      underef:
        skipRecvDeref: false # default true
  gocyclo:
    min-complexity: 15 # default 30
  goimports:
    local-prefixes: github.com/maratori/idescriptive
  godot:
    check-all: true # default false
  golint:
    min-confidence: 0 # default 0.8
  gomnd:
    settings:
      mnd:
        # the list of enabled checks, see https://github.com/tommy-muehle/go-mnd/#checks for description.
        checks: argument,case,condition,operation,return,assign # default argument,case,condition,operation,return,assign
        ignored-numbers: 0,1 # default 0,1
  lll:
    line-length: 120 # default 120
  maligned:
    suggest-new: true # default false
  misspell:
    locale: us
    ignore-words: "" # default: ""
  nakedret:
    max-func-lines: 0 # default 30
  nestif:
    min-complexity: 4 # default 5
  nolintlint:
    allow-unused: false # default false
    allow-leading-space: true # default true
    allow-no-explanation: [funlen] # default []
    require-explanation: true # default false
    require-specific: true # default false
  prealloc:
    simple: false # default true
    range-loops: true # default true
    for-loops: true # default false
  testpackage:
    skip-regexp: (export|internal)_test\.go # default (export|internal)_test\.go
  unparam:
    check-exported: true # default false
  wsl:
    strict-append: true # default true
    allow-assign-and-call: true # default true
    allow-multiline-assign: true # default true
    allow-case-trailing-whitespace: true # default true
    allow-cuddle-declarations: false # default false

linters:
  disable-all: true
  enable:
    ## enabled by default
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    ## disabled by default
    - asciicheck
    - bodyclose
    - dupl
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - lll
    - maligned
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - prealloc
    - rowserrcheck
    - scopelint
    - stylecheck
    - testpackage
    - unconvert
    - unparam
    - whitespace
    - wsl
    ## disabled
    #- depguard # is not used - Go linter that checks if package imports are in a list of acceptable packages
    #- dogsled # is not used - Checks assignments with too many blank identifiers (e.g. x, _, _, _, := f())
    #- goerr113 # too strict
    #- gofmt # replaced with goimports
    #- gomodguard
    #- interfacer # deprecated and has false positives

output:
  uniq-by-line: false # default true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
