language: go
go:
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"
env:
  global:
    - GO111MODULE=on
matrix:
  include:
    - go: "1.x"
      script:
        - make test-cover
        - make lint
        - make check-tidy
      after_success:
        - bash <(curl -s https://codecov.io/bash)
script:
  - make test
