name: ci
on:
  workflow_dispatch:
    inputs:
      debug_ssh:
        description: "Enable SSH debug with tmate, see https://github.com/marketplace/actions/debugging-with-tmate"
        required: false
        type: boolean
        default: false
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1" # Each Monday

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.18"
      - uses: golangci/golangci-lint-action@v6
        with:
          version: "v1.46.2"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.18"
      - name: Debug with tmate SSH if enabled
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_ssh }}
        uses: mxschmitt/action-tmate@v3
      - run: make test-cover
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  check-tidy:
    name: go mod tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.18"
      - run: make check-tidy
