name: ci
on:
  - push
  - pull_request
jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v1
        with:
          version: v1.27
  test:
    name: go test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1"
      - run: make test-cover
      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
  check-tidy:
    name: check go mod tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1"
      - run: make check-tidy
